### ISSUE TITLE
BUG: Neo-tree window "jumps" when opening files

### ISSUE THREAD

**Issue by georgeguimaraes** [nvim-neo-tree/neo-tree.nvim#1025]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

NVIM v0.10.0-dev-628+g3ecd45ded-Homebrew

### Operating System / Version

MacOS 14.0

### Describe the Bug

When browsing a code base with lots of directories opened (to fill up the neo-tree window and be able to scroll it), when I open a file that I have to scroll down to get to, the neo-tree window will jump to the top (see the video below). 

~~I've tracked the issue to `document_symbols`. When I don't have it enabled, no jumping occurs. The config below reproduces this problem.~~

### Screenshots, Traceback

https://github.com/nvim-neo-tree/neo-tree.nvim/assets/2929/3fd2831d-b301-426e-874a-9490d7c0e80e

### Steps to Reproduce

1. Open project
2. Expand a bunch of directories to fill up the screen
3. Open files that are close to the bottom of the neo-tree window

### Expected Behavior

The neo-tree window should not jump around when opening files. I managed to fix it by not enabling `document_symbols`. (I'm using LazyVim, and LazyVim enabled document_symbols).

### Your Configuration

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
}

local neotree_config = {
	"nvim-neo-tree/neo-tree.nvim",
	dependencies = { "MunifTanjim/nui.nvim", "nvim-tree/nvim-web-devicons", "nvim-lua/plenary.nvim" },
	cmd = { "Neotree" },
	keys = {
		{ "<Leader>e", "<Cmd>Neotree<CR>" }, -- change or remove this line if relevant.
	},
	opts = {
		sources = { "filesystem", "buffers", "git_status", "document_symbols" },
	},
}

table.insert(plugins, neotree_config)
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by pysan3** [comment]
This should be a duplicate of #996.

Am I right?

**Comment by georgeguimaraes** [comment]
@pysan3 Could be. Feel free to close it, of course. 

I tried to trigger this behaviour with my left-side Neovim tree in qmk_firmware by opening and closing directories, but the window didn't jump.

However, when I opened files, it did trigger the same behaviour as my issue here. 

That is fixed if I remove "document_symbols" from the sources.

**Comment by pysan3** [comment]
> That is fixed if I remove "document_symbols" from the sources.

Hmm, this is weird. It might be caused by a different thing. 

I'll leave this opened and will look into this weekend if possible.

**Comment by georgeguimaraes** [comment]
Hey, it seems my hack of removing "document_symbols" from sources does not work anymore.

With a default repro.lua (no config on my end), I got this when browsing through some dirs and files:

https://github.com/nvim-neo-tree/neo-tree.nvim/assets/2929/c2af8981-6f57-4b54-9c7b-36ed37a42f45

You can see that the last 2 files I opened caused the Neotree window to jump back to the top.

Do you know any workaround?

**Comment by georgeguimaraes** [comment]
I think I found the problem:

When we open a new buffer that were not opened before, neovim emits a `BufAdd` event, which is translated into the `vim_buffer_added` event in neo-tree.

That event is used in https://github.com/nvim-neo-tree/neo-tree.nvim/blob/230ff118613fa07138ba579b89d13ec2201530b9/lua/neo-tree/sources/filesystem/init.lua#L371-L378

For some reason, that handler seems to be forcing a redraw, which causes the window to "jump to the top".

So a simple workaround I found is using this config:

 ```lua
	opts = {
		enable_opened_markers = false,
	},
 ```

That disables the above handler.

Also, I can see that #996 is caused by a different issue.

**Comment by georgeguimaraes** [comment]
Ok, now with a full-blown neovim config with lsps and so on, I still get the window scrolling to the top. That's because there's still this handler that calls  `manager.redraw`:

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/230ff118613fa07138ba579b89d13ec2201530b9/lua/neo-tree/sources/filesystem/init.lua#L355-L361

So, I also had to disable it using:

```lua
    opts = {
      enable_diagnostics = false,
      enable_opened_markers = false,
    },
```

Now my neo-tree window is not scrolling to the top anymore.

Is there a way to make `manager.redraw` to not have this problem?

**Comment by cseickel** [comment]
@georgeguimaraes to be clear it does not ever jump to the top for me, and probably not for many other people or we would have a lot more activity on this issue.

My first guess is that maybe there is a character in the path ofn your home directory that is causing a bug. We've had (still have?) bugs with non-ascii characters in paths before. I can especially see a problem if you have characters that are double width because lua handles string sizes in bytes and not characters.

Can you share the path to your home directory? What does `~` expand to?

**Comment by georgeguimaraes** [comment]
```shell
❯ pwd
/Users/george
❯ z analytics
❯ pwd
/Users/george/code/sourcelevel/analytics
```

The paths I'm using don't use non-ascii characters.

I may not have been clear, but the jumping to the top only happens when you open files that you need to scroll down to reach. So maybe not a lot a people are using neo-tree with a big nested dir structure? (I like to open a lot of dirs and keep them open).

**Comment by georgeguimaraes** [comment]
@cseickel All the problems I reported are solved when I use neovim v0.9.4. The redraws are not "moving" the window anymore.

I was using neovim head before.

**Comment by cseickel** [comment]
Fascinating...

**Comment by ghidalgo93** [comment]
Another note of interest, I was able to reproduce this using the minimal setup above as well as using the default [LazyVim setup](https://github.com/nvim-neo-tree/neo-tree.nvim). A coworker was confused when I asked them if they had experienced this and had them navigate to a project with explorer items that exceeded their max line number and was able to see them reproduce it as well. My guess as to why this isn't more widely reported would be the same as @georgeguimaraes 's, in that maybe not a lot a people are using neo-tree with a big nested dir structure.

**Comment by georgeguimaraes** [comment]
@ghidalgo93 btw, you should check #996. @miversen33 is doing work over there related to this issue.

**Comment by ghidalgo93** [comment]
Hmm, very strange - removed my nightly install for v0.9.4 and am still getting the same jumping behavior, I'm also seeing this behavior if I switch to nvim-tree however so I'm now curious if its a LazyVim issue. Will try back on my regular config when I get the chance. Thanks!

**Comment by ahacking** [comment]
@ghidalgo93  Same problem here, also using LazyVim out of the box, jumps around all over the place on a large tree after opening a file.

**Comment by georgeguimaraes** [comment]
Found the problem. 

I've bisected neovim and found the first commit that introduced the problem. It's commit https://github.com/neovim/neovim/commit/008154954791001efcc46c28146e21403f3a698b (https://github.com/neovim/neovim/pull/24824) and https://github.com/neovim/neovim/pull/24889 that changed how `nvim_buf_set_lines` works, and that's what Nui.nvim uses under the hood.

This change caused problems in various plugins, and I think we'll still see more plugins with problems to come.

I've opened PR #1274 with a fix for this issue.

**Comment by miversen33** [comment]
Would it make more sense to instead forward a commit to nui.nvim to correct this issue instead of patching around it?

**Comment by georgeguimaraes** [comment]
Thanks! 

Not sure if Nui.nvim should take care of this. I'm actually thinking that Neovim is at fault here. I'm not used to what should be the "correct" behavior for `nvim_buf_set_lines`, though.

Maybe @MunifTanjim can give some input here?

**Comment by miversen33** [comment]
> I'm not used to what should be the "correct" behavior for `nvim_buf_set_lines`, though.

This is a very good point. In either case though, Neo-tree is using nui to handle the buffer manipulation and as such, if there is an issue with the buffer manipulation it is between nui and neo-tree (IMO). Definitely something to have @cseickel  weigh in on as well. 

It might also make some sense to bring this up on the actual neovim repo too (if there isn't already an issue), even if just to get some clarity on what the expected behavior of `nvim_buf_set_lines` should be. There is alot of code changes in those 3 commits and I don't have the time currently to pick through them but maybe one of the neovim team can shed some light on what is going on here

**Comment by georgeguimaraes** [comment]
So it seems that the default behavior now is to display the lines that were inserted at the top of the buffer when using  `nvim_buf_set_lines`:

https://github.com/neovim/neovim/pull/24912/files#diff-3ed34500d7e4a48a8705a381853d0d16021225d4140677d4df454806bbd66927R1252

**Comment by MunifTanjim** [comment]
I opened a related discussion https://github.com/neovim/neovim/discussions/25883 a while back. Got no response tho.

Those behavior changes of `nvim_buf_set_lines` and `nvim_buf_set_text` are causing issues with a whole bunch of plugins.
