### ISSUE TITLE
use neo-tree as netrw replacement?

### ISSUE THREAD

**Issue by max107** [nvim-neo-tree/neo-tree.nvim#23]
it's possible?

**Comment by cseickel** [comment]
There is no built in feature to enable this behavior. It could always be added if enough people are interested.

**Comment by nyngwang** [comment]
@cseickel  When I run `nvim MyFolder` it's netrw be opened. I would like to have neo-tree to be opened.

**Comment by cseickel** [comment]
@max107 @nyngwang @danilshvalov 
Question for anyone following this issue, now or in the future: If Neo-tree opens when you open a directory in nvim instead of netrw, what then happens when you open a file from the tree?

A. The current behavior, which is to create a split for the file you open and make Neo-tree a sidebar.
B. Behave like netrw and have the file take over the current window.

Second question, is the netrw replacement request:

C. mostly about what happens when opening a directory, or 
D. mostly allowing the tree to be browsed in place of the target window instead of as a separate sidebar
E. equally about both aspects of netrw

**Comment by nyngwang** [comment]
> A. The current behavior, which is to create a split for **the file** you open and make Neo-tree a sidebar.
> B. Behave like netrw and have the file take over the current window.

My cases is not considered: Most of the time I prefer to run `nvim project` instead of `nvim proj_file`. I will provide my opinion once this is considered.

**Comment by cseickel** [comment]
@nyngwang I think what you are saying, based on this and other conversations, is that you want to fluidly move between netrw style, sidebar, and floats depending on the situation. Is that accurate?

I don't think I posed the first question clearly. Let me restate to make sure there is no misunderstanding:

1. You open nvim with `nvim project_folder`
2. The only window is Neo-tree, opened to the folder you specified just like netrw would do
3. You find the file you want to open and open it.
4. Does that file now:
  A. open in a split, leaving Neo-tree as a sidebar in your preferred position?
  B. take over the current window, replacing Neo-tree?

I think it sounds like you choose A and C, because it is the most open ended solution that is the quickest path to "all of the above"

**Comment by nyngwang** [comment]
> is that you want to fluidly move between netrw style, sidebar, and floats depending on the situation. Is that accurate?

The problem of nvim-tree.lua is that it **doesn't** provide a floating tree so in my past experience with it this is now that accurate.

**Comment by cseickel** [comment]
> Why? Personally, I do this because when the filetree occupies the entire window, the content is left-aligned, but I like to be shown near the center of my screen (so why I set my the default position on the right side)

That was the missing piece of information that was confusing me! Wouldn't it be more efficient if step 2 was changed so that:

1. You open nvim with nvim project_folder
2. **There is an empty buffer, with Neo-tree also open and focused in your preferred position, as specified in your config** (left, right, or float)
3. You find the file you want to open and open it.
4. Nothing unusual happens here...

**Comment by nyngwang** [comment]
@cseickel: I like this one :) I think people would like to see everything organized "their-way" before making the first decision too!

**Comment by cseickel** [comment]
OK, here's a proposal on how to handle these requests:

- Add a `hijack_netrw` option that makes Neo-tree handle opening directories
- In that situation, Neo-tree will open as specified in your config
- Add a new window.position value as an option in that config: `in-place`, meaning netrw style in the same window where it was called from
- Include new vim command variations that allow overriding your default position with whatever suits you at the moment, to be handled in #31 
- If Neo-tree was opened with a position of `in-place`, then files will opened in the same window. If not, it will pick a window using the current logic designed for sidebars and floats.

I think this covers all possible variations of what people may want. I'll let this sit for at least a few days to collect comments.

**Comment by cseickel** [comment]
Status update: I released part of this solution, which is that Neo-tree now hijacks netrw automatically. It will open in whatever position you have specified in your config when you open a directory in nvim. If anyone actually wants to use netrw as an option, let me know and I'll put in a flag to disable this functionality.

What we don't have yet is the new "in-place" position option, we are still limited to sidebar or floating window. I am still working on the "in-place" option.

**Comment by cseickel** [comment]
This is in **main** right now and I think it is done. I changed the position name from "in-place" to "split". If you want to use netrw style all the time, set `"split"` as your position:

```lua
require("neo-tree").setup({
  filesystem = {
    window = {
      position = "split",
    },
  }
})
```

If you only want to use it as "split" style sometimes, use the new  "InSplit" commands:
```
NeoTreeRevealInSplit
NeoTreeRevealInSplitToggle
NeoTreeShowInSplit
NeoTreeShowInSplitToggle
```

**Comment by max107** [comment]
<img width="1515" alt="image" src="https://user-images.githubusercontent.com/862272/152925404-3028af72-36da-405b-82a9-8ca857a046ee.png">

**Comment by max107** [comment]
@cseickel i updated neo-tree to latest commit and problem still exists

**Comment by cseickel** [comment]
@max107 I think I got it this time.
