### ISSUE TITLE
RAM usage increases on each save if the window is open

### ISSUE THREAD

**Issue by shaksiper** [nvim-neo-tree/neo-tree.nvim#393]
I have been noticing this weird thing that each save action increases the RAM usage of nvim process.
I did some manual trouble shooting (I had to because there doesn't seem to be trivial way to monitor RAM usage within vim/neovim), and the result seems to be the neo-tree.

Steps to reproduce:
start neovim in the directory `nvim .`
open couple of files.
`:w` 10-20 times.

nvim starts with around **50MB RAM** usage, then after this process it becomes **100MB**, then stays that way. Memory is only deallocated when the neo-tree is closed (although I didn't thoroughly try this, if it always frees the memory when the window/panel is closed). It only increases without limit until the nvim prcess is killed by the OS.

Same behavior with regardless of (use_libuv_file_watcher = true) option.

Also I am using Linux with btrfs. I don't have a chance to try it on another file system.

**Comment by cseickel** [comment]
I usually start with eliminating diagnostics and git updates with any memory or performance issues. You can disable those with these settings:

```lua
require("neo-tree").setup({
  enable_diagnostics = false,
  enable_git_status = false,
})
```

In addition to testing without those turned on, can you also tell me:

- What version of neovim?
- What version of neo-tree?
- What files are you working on?
- Have you tried repeating the steps in a different project?

**Comment by shaksiper** [comment]
I will do that the first chance I get and report back

**Comment by kamilez** [comment]
@cseickel I am facing the same problem and see that @shaksiper didn't respond yet so it would be nice to have it fixed since in large projects it seems to grow much faster than in directory with one file. My versions are:
- NVIM v0.8.0-dev-nightly-5-g1f1863ed5,
- latest (2.32),
- mostly go but I think it doesn't matter - I've tried in my project but also in empty directory and only one file within - it seems to take more saves in second case but still with ~100 writes it grows at least 2x,

**Comment by miversen33** [comment]
Be sure to investigate your LSPs as well. I've noticed sumneko is a huge memory hog/leak, but it took me a while to establish that

**Comment by cseickel** [comment]
@kamilez Did you try disabling git and diagnostics? They are the first things I look at for any performance or memory issues:

```lua
require("neo-tree").setup({
  enable_diagnostics = false,
  enable_git_status = false,
})
```

The hard part here is finding the particular thing that causes the memory leak. It doesn't happen for me so I can't do much about it until I find a way to recreate the issue.

**Comment by kamilez** [comment]
@cseickel I've tried also with init.lua as below. Cloned this repository. Launched nvim and neo-tree and was writing in README.md one letter ("a") per line - "a" then enter for next line and save with ":w" and this way 50 lines and 50 times save. Grew from 0.2 to 0.5% on 16GB RAM (in other bigger directory as mentioned above those numbers are higher). With nvim-tree can't exceed 0.2 that doesn't change since nvim launch and starting editing. No language server or any other plugins as below that would affect the process. Give me feedback if you reproduce it and see any difference. If not I will try to search on my own.

```
-- plugin configuration
require('packer').startup(function()
	-- plugin manager
	use 'wbthomason/packer.nvim'

	use {
		"nvim-neo-tree/neo-tree.nvim",
		branch = "v2.x",
		requires = { 
			"nvim-lua/plenary.nvim",
			"kyazdani42/nvim-web-devicons", -- not strictly required, but recommended
			"MunifTanjim/nui.nvim",
		}
	}
end)

require("neo-tree").setup({
	window = {
		width = 30
	},
	filesystem = {
	 	follow_current_file = true,
		filtered_items = {
			hide_dotfiles = false,
			hide_hidden = false,
			hide_gitignored = false
		}
	},
	enable_diagnostics = false,
	enable_git_status = false,
})
global_keymap('n', '<C-g>', ':NeoTreeShowToggle<CR>', global_keymap_opts)
```

**Comment by cseickel** [comment]
I'll give that a try later.

**Comment by cseickel** [comment]
@kamilez `global_keymap` and `global_keymap_opts` appear to be custom variables that are not included in your example `init.lua`. Can you provide the complete config you are using? Even better would be to use a minimal config.

**Comment by kamilez** [comment]
@cseickel fixed configuration above. Actually it was the whole file. I just forgot to remove this line and nvim didn't throw any error bacaude was launching with :NeoTreeShow. Tested again with eample above and still the same.

**Comment by cseickel** [comment]
Thanks @kamilez, I have recreated the leak you described using these instructions. I'll dig in and figure this out now.

**Comment by cseickel** [comment]
I think this is fixed, at least it seems to be foxed in the specific scenario that @kamilez described. Can you confirm?

**Comment by kamilez** [comment]
Unfortunately I did't notice much difference. Still on daily basis grows:
![image](https://user-images.githubusercontent.com/16545480/180719977-0c28d6d7-ad41-4809-869b-8f96c7d8b25b.png)

**Comment by cseickel** [comment]
> Unfortunately I did't notice much difference. Still on daily basis grows:

Is that using the specific config and steps you outlined above, or just using your normal config and workflow?

**Comment by kamilez** [comment]
@cseickel I've been using default value all the time and unfortunately toggling it doesn't fix the problem.

**Comment by cseickel** [comment]
It looks like that was just the thing triggering refreshes for me. It's just the file system navigate call (called on refresh in response to file watcher events) that has the leak. I'm zeroing in it, slowly but surely.

**Comment by cseickel** [comment]
This was accidentally closed. I'm still working on it.

**Comment by cseickel** [comment]
OK, between the fixes I have put in so far, and the latest fix in Nui (https://github.com/MunifTanjim/nui.nvim/pull/176), 99% of the memory leak issues are resolved.

TBH, I think there is still something small to find, but it doesn't increase exponentially and become a real issue.

Can you update to the latest in `main` and let me know if it is fixed now?

**Comment by kamilez** [comment]
@cseickel I didn't notice anymore any issues related with RAM after this change. Seems to be fixed. Thanks.

**Comment by cseickel** [comment]
> @cseickel I didn't notice anymore any issues related with RAM after this change. Seems to be fixed. Thanks.

Awesome, I'm going to close this issue now.

**Comment by hinell** [comment]
https://user-images.githubusercontent.com/8136158/227706226-02facfd2-1a48-4de0-8567-7812be0987b6.mov


@cseickel Please reopen this issue. The problem with RAM consumption is relevant again. The consumption in my case jumps from mere 42 MB to almost 200 MB (!) when `neo-tree` is opened. If I generate shortcuts from `defaults.lua` to make lists for `Legendary.nvim` plugin I can get easily over 500MB wasted per nvim instance! This should be fixed.

Nvim-tree is much better at handling this.

### My setup:

```lua
-- Init.lua
-- Packer plugin manager config
  ...
	use({
		"nvim-neo-tree/neo-tree.nvim",
		requires = { 
		  "nvim-lua/plenary.nvim",
		  "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
		  "MunifTanjim/nui.nvim"
		},
		config = function()
			require("neo-tree").setup({
				enable_diagnostics = false,
				enable_git_status = false,
				window = {
					position = "right"
				}
			})
		end
	})



```

```
NVIM v0.9.0-dev-434f3d6a
Kubuntu 22.04.2 LTS
```

**Comment by cseickel** [comment]
@hinell I don't think it's neo-tree that is using up that ram, maybe it's Legenedary.nvim. I don't have any problems at all with memory usage.

You shouldltry uninstalling all other plugins first and then doing the same test.

**Comment by hinell** [comment]
@cseickel Without Legendary it takes up 150 MB easily just after toggling it.

**Comment by cseickel** [comment]
Then it's definitely another plugin or some combination of plugins working together that create the memory leak. My memory usage goes up by 0.2 MB the first time I open neo-tree and it will not change at all just from toggling it open and closed.

**Comment by hinell** [comment]
The source of issue might be a dependency plugin (like `MunifTanjim/nui.nvim`) that messes things up. But I'm not sure. I haven't had any problems with RAM consumption before `neo-tree` installation.  May be this is because I'm using dev version of nvim?

**Comment by miversen33** [comment]
@hinell  I am not able to recreate the issue you experienced with the following configuration
```lua
-- Minimal configuration
-- mini.lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
        {
                'nvim-neo-tree/neo-tree.nvim',
                dependencies = {
                  "nvim-lua/plenary.nvim",
                  "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
                  "MunifTanjim/nui.nvim"
                },
                config = {
                        {
                                enable_diagnostics = false,
                                enable_git_status = false,
                                window = { postition = 'right' }
                        }
                }

        },
        {
                'mrjones2014/legendary.nvim',
        }
})
```

This is almost certainly an issue related to legendary. Regardless, even if it _is_ an issue with Neo-tree, you have not provided enough information to recreate it. **And** you have necro'ed an old issue that has been closed for months. Consider opening a new issue and providing both a minimal configuration (including your `legendary` configuration) and steps to recreate your issue. Or consider reaching out to the maintainers of `legendary` for guidance on how to debug memory leak issues with their plugin. 

In any case. There is no reason to necro an old thread with a tangential (at best) issue.

**Comment by hinell** [comment]
>This is almost certainly an issue related to legendary.

@miversen33 I've disabled `Legendary` temporarily and tested `neo-tree` again. The problem didn't go. `Legendary` isn't interfering with `neo-tree` in anyway, cause it's activated via separate shortcut or command.

**Comment by hinell** [comment]
>This is almost certainly an issue related to legendary.

@miversen33 That's certainly not. I've disabled `Legendary` temporarily and tested `neo-tree` again and the issue didn't go. 

`Legendary` can't be a problem cause it IS NOT interfering with `neo-tree` in anyway. It's just a dropdown for shortcuts.

**Comment by hinell** [comment]
@miversen33 Certainly not. `Legendary` isn't interfering with `neo-tree` in anyway. It can't be a problem. 
I've disabled `Legendary` and all others plugins and run the above config in a clean room nvim instance. It seems like the issue comes from enabled diagnostics. It takes up 170MB easily. Here is a config:

```lua 
....
     enable_diagnostics = true,
     enable_git_status = true,
```
With these enabled, it's wasting a lot of memory.

**Comment by miversen33** [comment]
Even with those options enabled I am not able to recreate the issue you refer to. Additionally, you have no right to demand anything of any project maintainer. I suggest this issue get locked. If @hinell is experiencing an issue, they should provide a way to reproduce it reliably, be less aggressive/toxic, and consider respecting others resources.

As it stands now, we do not have a way to recreate the issue you are experiencing. While I am not discounting it, as cannot recreate it and thus cannot debug it. I cannot lock this issue, thus I will simply suggest the Project maintainer lock it

**Comment by cseickel** [comment]
Agreed @miversen33.
