### ISSUE TITLE
Performance issue/unstable with recent commits?

### ISSUE THREAD

**Issue by tmpm697** [nvim-neo-tree/neo-tree.nvim#767]
this plugin became unstable with recent commits, the last stable one i can actually use is `d9e50c185f5728d8cb64943566449180b2903fd4` -- that's from last dec 2022.

recent ones cause my buffer `flick` when use with persisted.nvim to save/restore session. check this: https://github.com/olimorris/persisted.nvim/issues/51

**Comment by charbelnicolas** [comment]
I've completely stopped using neo-tree since the last few days for the same reasons, it's becoming very glitchy and lots of issues have been popping up...

**Comment by charbelnicolas** [comment]
Using neo-tree with sessions is messy too...

**Comment by tmpm697** [comment]
@cseickel : can you pump up a bit with new commits? currently not stable for usage.

**Comment by nhat-vo** [comment]
Hi! A few days ago, I pushed a PR to clean up invalid buffers caused by session restore. This might be the cause of the bugs that you have seen, and I'm very sorry for that 😞. However, I can't seem to reproduce the issue that you mentioned. Could you provide me with some steps on how to do this?

**Comment by tmpm697** [comment]
@nhat-vo : I used neotree with persisted.nvim as i mentioned in 1st post with linked issue.
basically i used events from autocmd from persisted.nvim that would close/re-open session before save/restore

so neotree should not store in the saved session, but i got issue that all buffers deleted and neotree randomly restored and sometime not.

also i'm observing cursor and some kind of error message after doing `:qa` that can related to neotree.

**Comment by nhat-vo** [comment]
@tmpm697 Could you provide a minimal config, please 😄?

**Comment by tmpm697** [comment]
just tried with all latest neotree and persisted.nvim again, got this error:
```
Error executing vim.schedule lua callback: ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/command/init.lua:165: Invalid window id: 1011
stack traceback:
▒░[C]: in function 'nvim_set_current_win'
▒░...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/command/init.lua:165: in function <...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/command/init.lua:163>
Error executing vim.schedule lua callback: ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/command/init.lua:165: Invalid window id: 1036
stack traceback:
▒░[C]: in function 'nvim_set_current_win'
▒░...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/command/init.lua:165: in function <...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/command/init.lua:163>
Error executing vim.schedule lua callback: ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/command/init.lua:165: Invalid window id: 1046
stack traceback:
▒░[C]: in function 'nvim_set_current_win'
▒░...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/command/init.lua:165: in function <...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/command/init.lua:163>
```

my neotree config:
```
return {
  -- file explorer
  "nvim-neo-tree/neo-tree.nvim",
  dependencies = {
    "nvim-lua/plenary.nvim",
    -- "nvim-tree/nvim-web-devicons",
    "MunifTanjim/nui.nvim",
  },
  cmd = "Neotree",
  -- commit = "d9e50c185f5728d8cb64943566449180b2903fd4", -- recent commits cause flick

  config = function()
    -- Unless you are still migrating, remove the deprecated commands from v1.x
    vim.cmd([[ let g:neo_tree_remove_legacy_commands = 1 ]])

    -- If you want icons for diagnostic errors, you'll need to define them somewhere:
    vim.fn.sign_define("DiagnosticSignError", { text = " ", texthl = "DiagnosticSignError" })
    vim.fn.sign_define("DiagnosticSignWarn", { text = " ", texthl = "DiagnosticSignWarn" })
    vim.fn.sign_define("DiagnosticSignInfo", { text = " ", texthl = "DiagnosticSignInfo" })
    vim.fn.sign_define("DiagnosticSignHint", { text = "", texthl = "DiagnosticSignHint" })
    -- NOTE: this is changed from v1.x, which used the old style of highlight groups
    -- in the form "LspDiagnosticsSignWarning"

    require("neo-tree").setup({
      use_default_mappings = false, -- no default mappings enable, define keybidings yourself
      close_if_last_window = false, -- Close Neo-tree if it is the last window left in the tab
      popup_border_style = "rounded",
      enable_git_status = true,
      enable_diagnostics = true,
      sort_case_insensitive = false, -- used when sorting files and directories in the tree
      sort_function = nil, -- use a custom function for sorting files and directories in the tree
      default_component_configs = {
        container = {
          enable_character_fade = true,
        },
        indent = {
          indent_size = 2,
          padding = 1, -- extra padding on left hand side
          -- indent guides
          with_markers = true,
          indent_marker = "│",
          last_indent_marker = "└",
          highlight = "NeoTreeIndentMarker",
          -- expander config, needed for nesting files
          with_expanders = nil, -- if nil and file nesting is enabled, will enable expanders
          expander_collapsed = "",
          expander_expanded = "",
          expander_highlight = "NeoTreeExpander",
        },
        icon = {
          folder_closed = "",
          folder_open = "",
          folder_empty = "ﰊ",
          -- The next two settings are only a fallback, if you use nvim-web-devicons and configure default icons there
          -- then these will never be used.
          default = "*",
          highlight = "NeoTreeFileIcon",
        },
        modified = {
          symbol = "[+]",
          highlight = "NeoTreeModified",
        },
        name = {
          trailing_slash = false,
          use_git_status_colors = true,
          highlight = "NeoTreeFileName",
        },
        git_status = {
          symbols = {
            -- Change type
            added = "", -- or "✚", but this is redundant info if you use git_status_colors on the name
            modified = "", -- or "", but this is redundant info if you use git_status_colors on the name
            deleted = "⊖", -- this can only be used in the git_status source
            renamed = "➜", -- this can only be used in the git_status source
            -- Status type
            untracked = "★",
            ignored = "◌",
            unstaged = "✗",
            staged = "✓",
            conflict = "",
          },
        },
      },
      window = {
        position = "left",
        width = 40,
        mapping_options = {
          noremap = true,
          nowait = true,
        },
        mappings = {
          ["<space>"] = {
            "toggle_node",
            nowait = false, -- disable `nowait` if you have existing combos starting with this char that you want to use
          },
          ["<tab>"] = "open",
          ["<cr>"] = "open",
          ["P"] = { "toggle_preview", config = { use_float = true } },
          ["s"] = "open_vsplit",
          ["z"] = "close_all_nodes",
          ["Z"] = "expand_all_nodes",
          ["a"] = {
            "add",
            config = {
              show_path = "none", -- "none", "relative", "absolute"
            },
          },
          ["A"] = "add_directory", -- also accepts the optional config.show_path option like "add". this also supports BASH style brace expansion.
          ["d"] = "delete",
          ["r"] = "rename",
          ["y"] = "copy_to_clipboard",
          ["x"] = "cut_to_clipboard",
          ["p"] = "paste_from_clipboard",
          ["c"] = "copy", -- takes text input for destination, also accepts the optional config.show_path option like "add":
          ["m"] = "move", -- takes text input for destination, also accepts the optional config.show_path option like "add".
          ["q"] = "close_window",
          ["R"] = "refresh",
          ["?"] = "show_help",
          ["<"] = "prev_source",
          [">"] = "next_source",
        },
      },
      nesting_rules = {},
      filesystem = {
        filtered_items = {
          visible = false, -- when true, they will just be displayed differently than normal items
          hide_dotfiles = true,
          hide_gitignored = true,
          hide_hidden = true, -- only works on Windows for hidden files/directories
          hide_by_name = {
            --"node_modules"
          },
          hide_by_pattern = { -- uses glob style patterns
            --"*.meta",
            --"*/src/*/tsconfig.json",
          },
          always_show = { -- remains visible even if other settings would normally hide it
            --".gitignored",
          },
          never_show = { -- remains hidden even if visible is toggled to true, this overrides always_show
            --".DS_Store",
            --"thumbs.db"
          },
          never_show_by_pattern = { -- uses glob style patterns
            --".null-ls_*",
          },
        },
        follow_current_file = true, -- NOTE: -- This will find and focus the file in the active buffer every
        group_empty_dirs = false, -- when true, empty folders will be grouped together
        hijack_netrw_behavior = "open_current", --NOTE: -- netrw disabled, opening a directory opens neo-tree
        use_libuv_file_watcher = false, -- This will use the OS level file watchers to detect changes
        window = {
          mappings = {
            -- ["<bs>"] = "navigate_up",
            ["-"] = "navigate_up",
            ["."] = "set_root",
            ["H"] = "toggle_hidden",
            -- ["/"] = "fuzzy_finder",
            ["/"] = "filter_on_submit",
            ["D"] = "fuzzy_finder_directory",
            -- ["f"] = "filter_on_submit",
            ["f"] = "fuzzy_finder",
            ["<c-x>"] = "clear_filter",
            ["[g"] = "prev_git_modified",
            ["]g"] = "next_git_modified",
          },
        },
      },
      buffers = {
        follow_current_file = true, -- This will find and focus the file in the active buffer every
        -- time the current file is changed while the tree is open.
        group_empty_dirs = true, -- when true, empty folders will be grouped together
        show_unloaded = true,
        window = {
          mappings = {
            ["bd"] = "buffer_delete",
            ["<bs>"] = "navigate_up",
            ["."] = "set_root",
          },
        },
      },
      git_status = {
        window = {
          position = "float",
          mappings = {
            ["A"] = "git_add_all",
            ["gu"] = "git_unstage_file",
            ["ga"] = "git_add_file",
            ["gr"] = "git_revert_file",
            ["gc"] = "git_commit",
            ["gp"] = "git_push",
            ["gg"] = "git_commit_and_push",
          },
        },
      },

    })

  end,
}


```

**Comment by tmpm697** [comment]
tried with this and expect result to close neotree when save and open neotree after loading with `telescope.nvim`:
```
autocmd({ "User" }, {
	pattern = "PersistedSavePre",
	group = augroup,
	callback = function()
		pcall(vim.cmd, "Neotree action=close")
	end,
})

autocmd({ "User" }, {
	pattern = "PersistedTelescopeLoadPre",
	group = augroup,
	callback = function(session)
		vim.schedule(function()
			pcall(vim.cmd, "SessionSave")
			pcall(vim.cmd, "silent %bd!")
		end)
		-- vim.api.nvim_input("<ESC>:SessionSave<CR>")
		-- vim.api.nvim_input("<ESC>:%bd!<CR>")
		-- print(session.data.branch) -- Print the session's branch
	end,
})

autocmd({ "User" }, {
	pattern = "PersistedTelescopeLoadPost",
	group = augroup,
	callback = function(session)
		pcall(vim.cmd, "Neotree action=show")
	end,
})
```

**Comment by nhat-vo** [comment]
I see. The issue here is that #761 added a hook to close any neo-tree buffer on session load, and this also closes the neo-tree buffer that you loaded in `PersistedTelescopeLoadPost`. I will add a more rigorous check for invalid buffers so that `neo-tree` buffers created on autocmds like this are not closed.

**Comment by nhat-vo** [comment]
@tmpm697 I just pushed #771, which fixes the flick you mentioned. Other than that, do you have any issue?

**Comment by charbelnicolas** [comment]
I'm using [Workspaces Nvim](https://github.com/natecraddock/workspaces.nvim) and using this:

```
require('workspaces').setup({
	hooks = {
		open_pre = { 'NeoTreeClose', 'SessionsStop', 'silent %bdelete!' },
		open = { function() require('sessions').load('.nvim/session', { silent = true }) end, 'Neotree show filesystem' }
	}
})
```
and this is what I get:

https://user-images.githubusercontent.com/14960414/221302338-620ff0ef-e70a-4ba7-a304-0b016465dc34.mp4

This works perfectly with Nvim Tree:

https://user-images.githubusercontent.com/14960414/221302850-b23cd00e-9f29-4882-bb0e-835fe6e1cbed.mp4

Neo Tree closes itself automagically...

**Comment by nhat-vo** [comment]
@charbelnicolas #771 (just got merged into `main`) should fix this bug. If you have time, try switching to `main` and let me know if the problem persists. Again, I'm very sorry for the inconvenience 😥.

**Comment by tmpm697** [comment]
@nhat-vo main LGFM.

**Comment by charbelnicolas** [comment]
> @charbelnicolas #771 (just got merged into `main`) should fix this bug. If you have time, try switching to `main` and let me know if the problem persists. Again, I'm very sorry for the inconvenience 😥.

This did not fix the issue I'm having. IMO, neo tree shouldn't close anything automagically because it leads to these kinds of issues.

**Comment by nhat-vo** [comment]
@charbelnicolas So was the bug fixed for you? The closing was just there to avoid any collision (in #740), which might cause neo-tree to behave incorrectly.

**Comment by charbelnicolas** [comment]
> @charbelnicolas So was the bug fixed for you? The closing was just there to avoid any collision (in #740), which might cause neo-tree to behave incorrectly.

Yes, thank you

**Comment by nhat-vo** [comment]
Closing as solved.
